import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PUBLIC=path.join(__dirname,'public');
const PORT=Number(process.env.DRAGON_SAGA_PORT||process.env.PORT||4173);
const MAX_BODY=64*1024*1024;
const rooms=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.mp3':'audio/mpeg','.ogg':'audio/ogg','.wav':'audio/wav','.m4a':'audio/mp4','.woff':'font/woff','.woff2':'font/woff2'};
const securityHeaders={'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; media-src 'self' blob: data:; font-src 'self' blob: data:; connect-src 'self'; object-src 'none'; base-uri 'none'",'Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN'};
const clone=value=>value===undefined?undefined:structuredClone(value);
function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
function roomFor(code){if(!rooms.has(code))rooms.set(code,{state:null,revision:0,clients:new Set(),sessions:new Map(),ownerKey:null,touched:Date.now()});return rooms.get(code)}
function authToken(req,url){return String(req.headers.authorization||'').match(/^Bearer\s+(.+)$/i)?.[1]||url.searchParams.get('token')||''}
function sessionFor(room,req,url){const s=room.sessions.get(authToken(req,url))||null;if(s)s.touched=Date.now();return s}
function membersFor(room){return[...room.sessions.values()].map(s=>({clientId:s.clientId,name:s.name,role:s.role,characterId:s.characterId||null,mediaEditor:Boolean(room.state?.permissions?.mediaEditors?.includes(s.clientId))}))}
function overlay(room){const members=membersFor(room);return{members,owners:Object.fromEntries(members.filter(m=>m.role==='player'&&m.characterId).map(m=>[m.characterId,m.clientId])),gmClientId:members.find(m=>m.role==='gm')?.clientId||null}}
function sanitizeCampaign(value){const s=clone(value);if(!s||typeof s!=='object'||s.schema!=='dragon-saga-campaign')throw Object.assign(new Error('Invalid Dragon Saga campaign'),{status:400});s.session={};delete s.network;return s}
function stateForSession(room,session){if(!room.state)return null;const visible=clone(room.state);visible.network=overlay(room);if(!session||session.role!=='gm'){
 const ownId=session?.characterId||null;const positioned=new Set(Object.keys(visible.battle?.positions||{}));
 visible.characters=(visible.characters||[]).filter(c=>c.id===ownId||(visible.permissions?.partySheetView&&c.role==='hero'&&c.visibility!=='private'&&c.visibility!=='gm')||(c.role==='enemy'&&positioned.has(c.id))).map(c=>{if(c.id!==ownId){delete c.sourceText;delete c.gmNotes;delete c.audit}return c});
 if(visible.journal){visible.journal.personal=ownId&&visible.journal.personal?.[ownId]?{[ownId]:visible.journal.personal[ownId]}:{} }
 if(visible.world){visible.world.locations=(visible.world.locations||[]).filter(x=>x.discovered).map(x=>{delete x.gmNotes;return x});visible.world.routes=(visible.world.routes||[]).filter(x=>x.available!==false).map(x=>{delete x.gmNotes;return x})}
 visible.cities=(visible.cities||[]).filter(c=>c.available).map(c=>({...c,merchants:(c.merchants||[]).filter(m=>m.available).map(m=>({...m,stock:(m.stock||[]).filter(i=>i.available)}))}));
 visible.content={items:[],actions:[],creatures:[],mods:[]};
 }
 return visible
}
function broadcast(room,sender=null){for(const client of [...room.clients]){try{const session=room.sessions.get(client.token)||null;client.response.write(`data: ${JSON.stringify({state:stateForSession(room,session),revision:room.revision,sender})}\n\n`)}catch{room.clients.delete(client)}}}
function readBody(req){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>MAX_BODY){reject(new Error('Payload too large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function claimedByAnother(room,id,token){return id&&[...room.sessions].some(([other,s])=>other!==token&&s.role==='player'&&s.characterId===id)}
function registerSession(room,body){const priorToken=String(body.sessionToken||''),prior=room.sessions.get(priorToken);const token=prior?priorToken:randomUUID();let role='player',ownerKey=null;if(body.role==='gm'){if(!room.ownerKey){room.ownerKey=randomUUID()+randomUUID();ownerKey=room.ownerKey;role='gm'}else if(String(body.ownerKey||'')===room.ownerKey||prior?.role==='gm')role='gm'}let characterId=role==='player'?(String(body.characterId||'')||null):null,warning='';if(characterId){const hero=room.state?.characters?.find(c=>c.id===characterId&&c.role==='hero');if((room.state&&!hero)||claimedByAnother(room,characterId,token)){characterId=null;warning='Герой уже занят или отсутствует в кампании'}}const session={token,clientId:String(body.clientId||prior?.clientId||randomUUID()).slice(0,100),name:String(body.name||prior?.name||'Игрок').trim().slice(0,80)||'Игрок',role,characterId,touched:Date.now()};room.sessions.set(token,session);room.touched=Date.now();return{session,ownerKey,warning}}
function activeId(state){if(!state?.battle?.active)return null;return state.battle.order?.[state.battle.turnIndex]||null}
function safeNumber(next,current,min=-Infinity,max=Infinity){const n=Number(next);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):current}
function tradeQuantity(value){const n=Number(value);return Number.isSafeInteger(n)&&n>=0?n:null}
function inventoryQuantityByName(items){const totals=new Map();for(const item of items||[]){const name=String(item?.name||'').trim(),quantity=tradeQuantity(item?.quantity??1);if(!name||quantity===null)return null;totals.set(name,(totals.get(name)||0)+quantity)}return totals}
function sameTotals(a,b){if(!a||!b||a.size!==b.size)return false;for(const[key,value]of a)if(Math.abs(value-(b.get(key)||0))>1e-6)return false;return true}
function economyChanged(currentOwn,incomingOwn){if(Number(currentOwn?.currency?.gp||0)!==Number(incomingOwn?.currency?.gp||0)||Number(currentOwn?.currency?.sp||0)!==Number(incomingOwn?.currency?.sp||0)||Number(currentOwn?.currency?.cp||0)!==Number(incomingOwn?.currency?.cp||0))return true;return !sameTotals(inventoryQuantityByName(currentOwn?.inventory),inventoryQuantityByName(incomingOwn?.inventory))}
function applyShopTransactions(current,incoming,next,currentOwn,incomingOwn){
 const nextOwn=next.characters.find(x=>x.id===currentOwn.id);nextOwn.currency=clone(currentOwn.currency||{gp:0,sp:0,cp:0});nextOwn.inventory=clone(currentOwn.inventory||[]);
 const buys=[],stockSales=[],newStockSales=[];let malformed=false;
 for(const city of current.cities||[]){const ic=(incoming.cities||[]).find(x=>x.id===city.id);if(!ic)continue;for(const merchant of city.merchants||[]){const im=ic.merchants?.find(x=>x.id===merchant.id);if(!im)continue;
  for(const item of merchant.stock||[]){const ii=(im.stock||[]).find(x=>x.id===item.id);if(!ii)continue;const before=tradeQuantity(item.quantity||0),after=tradeQuantity(ii.quantity||0);if(before===null||after===null){malformed=true;continue}const delta=after-before;if(delta<0)buys.push({city,merchant,item,count:-delta});else if(delta>0)stockSales.push({city,merchant,item,count:delta})}
  for(const ii of im.stock||[])if(!(merchant.stock||[]).some(x=>x.id===ii.id)){const count=tradeQuantity(ii.quantity||0);if(count===null||!String(ii.name||'').trim())malformed=true;else if(count>0)newStockSales.push({city,merchant,item:ii,count})}
 }}
 const hasTrade=buys.length||stockSales.length||newStockSales.length;
 if(!hasTrade){if(economyChanged(currentOwn,incomingOwn))throw Object.assign(new Error('Inventory and currency changes require a valid merchant transaction'),{status:403});return}
 const available=op=>op.city.available!==false&&op.merchant.available!==false&&(op.item.available!==false||newStockSales.includes(op));
 if(malformed||[...buys,...stockSales,...newStockSales].some(op=>!available(op)))throw Object.assign(new Error('Invalid or unavailable merchant transaction'),{status:403});
 const incomingById=new Map((incomingOwn.inventory||[]).map(item=>[item.id,item]));const soldByName=new Map(),soldById=new Map();
 for(const item of currentOwn.inventory||[]){const before=tradeQuantity(item.quantity??1),afterItem=incomingById.get(item.id),after=afterItem?tradeQuantity(afterItem.quantity??1):0;if(before===null||after===null||after>before){if(after!==before)malformed=true;continue}const sold=before-after;if(sold){soldById.set(item.id,sold);soldByName.set(item.name,(soldByName.get(item.name)||0)+sold)}}
 const stockSoldByName=new Map();for(const op of [...stockSales,...newStockSales]){const name=String(op.item.name||'').trim();stockSoldByName.set(name,(stockSoldByName.get(name)||0)+op.count)}
 if(malformed||!sameTotals(soldByName,stockSoldByName))throw Object.assign(new Error('Sold inventory does not match merchant stock'),{status:403});
 let buyCost=0,sellValue=0;for(const op of buys){const quantity=tradeQuantity(op.item.quantity||0),price=Number(op.item.price||0);if(quantity===null||op.count>quantity||!Number.isFinite(price)||price<0)malformed=true;buyCost+=op.count*price}
 for(const[itemId,count]of soldById){const item=(currentOwn.inventory||[]).find(x=>x.id===itemId);const rates=[...stockSales,...newStockSales].filter(op=>String(op.item.name||'').trim()===item.name).map(op=>Number(op.merchant.buyRate??.5));const rate=rates[0];if(!Number.isFinite(rate)||rate<0||rate>1||rates.some(x=>Math.abs(x-rate)>1e-9))malformed=true;sellValue+=count*Number(item.value||0)*rate}
 const oldGp=Number(currentOwn.currency?.gp||0),expectedGp=Math.round((oldGp-buyCost+sellValue)*100)/100,incomingGp=Number(incomingOwn.currency?.gp||0);
 if(malformed||expectedGp<0||!Number.isFinite(incomingGp)||Math.abs(incomingGp-expectedGp)>1e-6||Number(incomingOwn.currency?.sp||0)!==Number(currentOwn.currency?.sp||0)||Number(incomingOwn.currency?.cp||0)!==Number(currentOwn.currency?.cp||0))throw Object.assign(new Error('Merchant payment does not match the transaction'),{status:403});
 const projected=clone(currentOwn.inventory||[]);for(const[itemId,count]of soldById){const item=projected.find(x=>x.id===itemId);item.quantity=tradeQuantity(item.quantity??1)-count}for(const op of buys){let item=projected.find(x=>x.name===op.item.name);if(item)item.quantity=tradeQuantity(item.quantity??1)+op.count;else{const candidate=(incomingOwn.inventory||[]).find(x=>x.name===op.item.name&&!projected.some(y=>y.id===x.id));item={id:String(candidate?.id||randomUUID()).slice(0,160),name:String(op.item.name).slice(0,160),quantity:op.count,weight:Math.max(0,Number(op.item.weight||0)),description:String(op.item.description||'').slice(0,5000),value:Math.max(0,Number(op.item.price||0)),equippedSlot:''};projected.push(item)}}
 const cleanProjected=projected.filter(x=>tradeQuantity(x.quantity??1)>0);if(!sameTotals(inventoryQuantityByName(cleanProjected),inventoryQuantityByName(incomingOwn.inventory)))throw Object.assign(new Error('Purchased inventory does not match merchant stock'),{status:403});
 nextOwn.currency.gp=expectedGp;nextOwn.inventory=cleanProjected;
 for(const op of buys){const item=next.cities.find(x=>x.id===op.city.id)?.merchants.find(x=>x.id===op.merchant.id)?.stock.find(x=>x.id===op.item.id);if(item)item.quantity-=op.count}
 for(const op of stockSales){const item=next.cities.find(x=>x.id===op.city.id)?.merchants.find(x=>x.id===op.merchant.id)?.stock.find(x=>x.id===op.item.id);if(item)item.quantity+=op.count}
 for(const op of newStockSales){const merchant=next.cities.find(x=>x.id===op.city.id)?.merchants.find(x=>x.id===op.merchant.id);const owned=(currentOwn.inventory||[]).find(x=>x.name===op.item.name);merchant.stock.push({id:String(op.item.id||randomUUID()).slice(0,160),name:String(owned.name).slice(0,160),price:Math.max(0,Number(owned.value||0)),quantity:op.count,weight:Math.max(0,Number(owned.weight||0)),description:String(owned.description||'').slice(0,5000),available:true})}
 nextOwn.equipment=clone(incomingOwn.equipment||currentOwn.equipment||{});const ids=new Set(nextOwn.inventory.map(x=>x.id));for(const slot of Object.keys(nextOwn.equipment))if(!ids.has(nextOwn.equipment[slot]))nextOwn.equipment[slot]=null
}
function normalizeEquipment(nextOwn,incomingOwn){const slots=['armor','mainHand','offHand','accessory'],ids=new Set((nextOwn.inventory||[]).map(x=>x.id));nextOwn.equipment={};for(const slot of slots){const id=incomingOwn.equipment?.[slot];nextOwn.equipment[slot]=ids.has(id)?id:null}for(const item of nextOwn.inventory||[])item.equippedSlot='';for(const slot of slots){const item=(nextOwn.inventory||[]).find(x=>x.id===nextOwn.equipment[slot]);if(item)item.equippedSlot=slot}}
function validAdvance(current,incoming){const order=current.battle?.order||[];if(!order.length)return false;let ti=current.battle.turnIndex+1,round=current.battle.round;if(ti>=order.length){ti=0;round++}return incoming.battle?.turnIndex===ti&&incoming.battle?.round===round}
function applyPlayerState(room,session,incomingRaw){const current=room.state,incoming=incomingRaw,next=clone(current),ownId=session.characterId;if(!ownId)throw Object.assign(new Error('No hero assigned'),{status:403});const currentOwn=current.characters?.find(c=>c.id===ownId&&c.role==='hero'),incomingOwn=incoming.characters?.find(c=>c.id===ownId);if(!currentOwn||!incomingOwn)throw Object.assign(new Error('Assigned hero is missing'),{status:403});
 const ownIndex=next.characters.findIndex(c=>c.id===ownId);next.characters[ownIndex]={...clone(incomingOwn),id:currentOwn.id,role:'hero',visibility:currentOwn.visibility,ownerId:currentOwn.ownerId,gmNotes:currentOwn.gmNotes,sourceText:currentOwn.sourceText,audit:currentOwn.audit};
 if(next.journal){next.journal.personal={...(next.journal.personal||{})};next.journal.personal[ownId]=String(incoming.journal?.personal?.[ownId]??next.journal.personal[ownId]??'').slice(0,250000);if(current.permissions?.playerJournalShared)next.journal.party=String(incoming.journal?.party??next.journal.party).slice(0,250000)}
 applyShopTransactions(current,incoming,next,currentOwn,incomingOwn);normalizeEquipment(next.characters[ownIndex],incomingOwn);
 if(current.permissions?.mediaEditors?.includes(session.clientId))next.assets=clone(incoming.assets||current.assets||[]);
 const ownsTurn=activeId(current)===ownId;if(ownsTurn&&incoming.battle){const onField=new Set(Object.keys(current.battle.positions||{}));for(const id of onField){const src=incoming.characters?.find(c=>c.id===id),dst=next.characters.find(c=>c.id===id);if(!src||!dst||id===ownId)continue;dst.hp=safeNumber(src.hp,dst.hp,0,dst.maxHp);dst.tempHp=safeNumber(src.tempHp,dst.tempHp,0,999);dst.conditions=Array.isArray(src.conditions)?src.conditions.slice(0,30).map(String):dst.conditions;dst.deathSaves=clone(src.deathSaves||dst.deathSaves)}
  next.battle.positions[ownId]=String(incoming.battle.positions?.[ownId]||next.battle.positions[ownId]);next.battle.movement[ownId]=safeNumber(incoming.battle.movement?.[ownId],next.battle.movement[ownId],0,Number(currentOwn.speed||30));next.battle.flags[ownId]=clone(incoming.battle.flags?.[ownId]||next.battle.flags[ownId]);next.battle.targetId=String(incoming.battle.targetId||'')||null;next.battle.result=clone(incoming.battle.result||null);next.battle.log=clone((incoming.battle.log||[]).slice(-150));if(validAdvance(current,incoming)){next.battle.turnIndex=incoming.battle.turnIndex;next.battle.round=incoming.battle.round;const newId=next.battle.order[next.battle.turnIndex];if(newId){next.battle.movement[newId]=safeNumber(incoming.battle.movement?.[newId],next.characters.find(c=>c.id===newId)?.speed||30,0,200);next.battle.flags[newId]=clone(incoming.battle.flags?.[newId]||{})}} }
 next.meta.updatedAt=new Date().toISOString();return next
}
async function serveStatic(req,res){let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{return json(res,400,{error:'Bad path'})}const requested=pathname==='/'?'/index.html':pathname;const absolute=path.resolve(PUBLIC,'.'+requested);if(!absolute.startsWith(PUBLIC+path.sep)&&absolute!==PUBLIC)return json(res,403,{error:'Forbidden'});try{const info=await stat(absolute);if(!info.isFile())throw new Error();const data=await readFile(absolute),ext=path.extname(absolute).toLowerCase();res.writeHead(200,{...securityHeaders,'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-store':'public, max-age=3600'});res.end(data)}catch{if(!path.extname(requested)){try{const data=await readFile(path.join(PUBLIC,'index.html'));res.writeHead(200,{...securityHeaders,'Content-Type':mime['.html'],'Cache-Control':'no-store'});return res.end(data)}catch{}}json(res,404,{error:'Not found'})}}
export function createHttpServer(){return http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');const match=url.pathname.match(/^\/api\/rooms\/([A-ZА-Я0-9_-]{1,12})\/(state|events|session|assignment)$/i);if(match){const code=match[1].toUpperCase(),action=match[2].toLowerCase(),room=roomFor(code);
 if(action==='assignment'&&req.method==='POST'){try{const owner=sessionFor(room,req,url);if(owner?.role!=='gm')return json(res,403,{error:'Only the room master can assign heroes'});const body=await readBody(req),clientId=String(body.clientId||''),characterId=String(body.characterId||'')||null,target=[...room.sessions.values()].find(s=>s.role==='player'&&s.clientId===clientId);if(!target)return json(res,404,{error:'Player session not found'});if(characterId&&!room.state?.characters?.some(c=>c.id===characterId&&c.role==='hero'))return json(res,400,{error:'Hero not found'});if(characterId)for(const member of room.sessions.values())if(member!==target&&member.role==='player'&&member.characterId===characterId)member.characterId=null;target.characterId=characterId;room.revision++;room.touched=Date.now();broadcast(room,owner.clientId);return json(res,200,{ok:true,characterId,members:membersFor(room),revision:room.revision})}catch(error){return json(res,error.message==='Payload too large'?413:400,{error:error.message})}}
 if(action==='session'&&req.method==='DELETE'){const token=authToken(req,url);if(!room.sessions.has(token))return json(res,401,{error:'Room session required'});const departed=room.sessions.get(token);room.sessions.delete(token);room.revision++;broadcast(room,departed.clientId);return json(res,200,{ok:true,revision:room.revision})}
 if(action==='session'&&req.method==='POST'){try{const body=await readBody(req),{session,ownerKey,warning}=registerSession(room,body);if(room.state){room.revision++;broadcast(room,session.clientId)}return json(res,200,{ok:true,token:session.token,ownerKey,role:session.role,characterId:session.characterId,warning,state:stateForSession(room,session),revision:room.revision})}catch(error){return json(res,error.message==='Payload too large'?413:400,{error:error.message})}}
 if(action==='state'&&req.method==='GET'){const session=sessionFor(room,req,url);if(!session)return json(res,401,{error:'Room session required'});if(!room.state)return json(res,404,{error:'Empty room'});return json(res,200,{state:stateForSession(room,session),revision:room.revision})}
 if(action==='state'&&req.method==='POST'){try{const session=sessionFor(room,req,url);if(!session)return json(res,401,{error:'Room session required'});const body=await readBody(req);if(!body.state||typeof body.state!=='object')return json(res,400,{error:'Missing state'});if(Number(body.baseRevision)!==room.revision)return json(res,409,{error:'Revision conflict',state:stateForSession(room,session),revision:room.revision});if(!room.state){if(session.role!=='gm')return json(res,403,{error:'Only the room master can initialize a campaign'});room.state=sanitizeCampaign(body.state)}else room.state=session.role==='gm'?sanitizeCampaign(body.state):applyPlayerState(room,session,body.state);room.revision++;room.touched=Date.now();broadcast(room,session.clientId);return json(res,200,{ok:true,revision:room.revision,state:stateForSession(room,session)})}catch(error){return json(res,error.status||(error.message==='Payload too large'?413:400),{error:error.message})}}
 if(action==='events'&&req.method==='GET'){const session=sessionFor(room,req,url);if(!session)return json(res,401,{error:'Room session required'});res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': Dragon Saga room connected\n\n');const client={response:res,token:session.token};room.clients.add(client);if(room.state)res.write(`data: ${JSON.stringify({state:stateForSession(room,session),revision:room.revision,sender:null})}\n\n`);const ping=setInterval(()=>{try{res.write(': ping\n\n')}catch{}},20000);req.on('close',()=>{clearInterval(ping);room.clients.delete(client)});return}}
 if(url.pathname==='/api/health')return json(res,200,{ok:true,rooms:rooms.size,protocol:3,app:'dragon-saga'});serveStatic(req,res)})}
setInterval(()=>{const cutoff=Date.now()-12*60*60*1000;for(const[code,room]of rooms)if(room.touched<cutoff&&room.clients.size===0)rooms.delete(code)},30*60*1000).unref();
export function startServer({port=PORT,host='0.0.0.0'}={}){const server=createHttpServer();return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,()=>{const actualPort=server.address().port;console.log(`Dragon Saga is ready on http://${host}:${actualPort}`);resolve({server,port:actualPort,host})})})}
const isDirectRun=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);if(isDirectRun)startServer().catch(error=>{console.error(error);process.exitCode=1});
